### ISSUE TITLE
Bad results when transaction concerns credit repayment (tested with KBC coda)

### ISSUE THREAD

**Issue by tix02be** [wimverstuyf/php-coda-parser#10]
Hello, 

I use your parser for an app used in intern and I found a bug when a transaction is regarding a credit repayment operation (in my case VISA or simple Bank credit). It appears that the parser returns many "21" operations (which is ok regarding CODA specs at https://www.febelfin.be/sites/default/files/Standard-CODA-2.3-FR.pdf), but when parsed, only the last operation "21" is returned when the first was expected (the one with "sequence_number_detail" prop == 0000). 

To fix that in my app I simply added a condition in Parser.php before the line 156, so the code looks like this:
`if( $coda_line->sequence_number_detail == '0000' )`
`	$current_account_transaction->transactions[$trans_idx]->{'line'.$coda_line->record_code.$coda_line->article_code} = $coda_line;`

Don't know if all coda transactions will work with this "fix" but in my case that does the job.

Thanks for the great work !

**Comment by wimverstuyf** [comment]
Thx for the feedback. I'll check if the fix can be applied.
If you have an example file you can share where the issue pops up that would be great.

**Comment by tix02be** [comment]
Hi Wim, 

Here is a file you can test with.

[Réception CODA.2017-10-30.txt](https://github.com/wimverstuyf/php-coda-parser/files/1432025/Reception.CODA.2017-10-30.txt)

The file contains only one transaction: a credit repayment. As you see if you var_dump($coda_line) in Parser::convertToRaw, you'll get 3 lines "21" for this transaction.
* the line with sequence_number_detail=0000 is the final transaction amount
* 0001 = the repaid capital
* 0002 = the interest paid (so the amount of 0001 + the amount of 0002 = the amount of 0000).

Thank you !

**Comment by wimverstuyf** [comment]
Bug has been fixed in master.
