### ISSUE TITLE
Port to .NET

### ISSUE THREAD

**Issue by supervos** [wimverstuyf/php-coda-parser#13]
Hello,

I am searching for a coda parser in .NET. Your package is the only clear and understandable one that I have found.

Is it possible that I port your code to C# and place a link back to this project?
I will try to keep following updates in your project and replicate them in my project and raise issues for your code if some in my code arrive.

**Comment by wimverstuyf** [comment]
Hi,

Great to hear you want to port the library to C#. Of course this is not a problem (that's why it is open source anyway ;-) ).
When the port is ready I can place a link to your project.

**Comment by supervos** [comment]
Hello,

A version is present at https://github.com/supervos/coda-parser. It still needs a little bit cleanup but is almost ready for v1.

**Comment by wimverstuyf** [comment]
Nice. I've added a link to your project in the README file.
