### ISSUE TITLE
Change Request: User licence not GPL but LGPL

### ISSUE THREAD

**Issue by PeterGeens** [wimverstuyf/php-coda-parser#15]
For legal purposes LGPL is better licence for using this code in proprietary software.

**Comment by wimverstuyf** [comment]
I'm in favor of re-licensing the library to LGPL as it would be a better fit.
Does anyone disagree with this?

@Grummfy @jonaswouters @Thijs-Riezebeek

**Comment by jonaswouters** [comment]
sounds like an improvement

**Comment by Grummfy** [comment]
ok doki for me

**Comment by wimverstuyf** [comment]
Great! The license has been changed to LGPL.
