### ISSUE TITLE
Read sequence numbers

### ISSUE THREAD

**Issue by astalpaert** [wimverstuyf/php-coda-parser#17]
To be able to detect duplicate database entries, I need to check if a coda/transaction was already inserted (based on its sequence number). Since the sequence numbers were read/parsed, but not exposed to the transaction, I added these. 

`https://github.com/wimverstuyf/php-coda-parser/pull/16
`

**Comment by astalpaert** [comment]
Is it possible to update the package version? it's still on **v2.1.1** without the latest changes from last week.
Thanks a lot!

**Comment by wimverstuyf** [comment]
A new release v2.2 has just been created.
