### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by dono1309** [wimverstuyf/php-coda-parser#22]
Hello,

i've this error.
Can you help me ?
Parse error: syntax error, unexpected ')' in /var/www/indigona/logi_print/vendor/codelicious/php-coda-parser/src/StatementParsers/TransactionParser.php on line 108

thanks

**Comment by wimverstuyf** [comment]
Hi,

Which version of PHP are you using? At this line there is an extra comma just before the ')' which is allowed in more recent versions of PHP but not in older versions.
So this might be the problem.

			$transactionCode,
		);

**Comment by dono1309** [comment]
Hello,
It's the problem, i remove the comma and its ok 
my version of php : 
PHP 7.2.34-23+0~20210701.63+debian10~1.gbpd7cd48 (cli) (built: Jul  1 2021 16:12:59) ( NTS  )

Thanks :)

**Comment by wimverstuyf** [comment]
Ok great! The comma has been removed on the master branch.
