### ISSUE TITLE
CODA file version ?

### ISSUE THREAD

**Issue by DC22SP** [wimverstuyf/php-coda-parser#9]
What is the version of CODA files that this library handle ? as I see the CODA code that exists in /tests/ParserTest.php ( getSample1() ) method ) is different a lot from the documentation of CODA version 2.3 and version 2.5b (Ex.. EUR and BE in record type 1 and 8)

**Comment by wimverstuyf** [comment]
It's based on version 2.3. So it should work with the latest CODA-files, but if you find any errors I can look into it.
